[package]
authors = ["TheBlueFireFox <adrian.hornung@yahoo.de>"]
edition = "2018"
name = "chip8"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "chip"
path = "src/lib.rs"

[dependencies]
getrandom = {version = "0.2", features = ["js"]}
lazy_static = "1.4"
num = "0.3"
rand = {version = "0.8", features = ["getrandom"]}
zip = {version = "0.5", default-features = false, features = ["deflate"]}

# just for debugging
js-sys = "0.3"
wasm-bindgen = "0.2.70"
web-sys = {version = "0.3", default-features = false, features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'console'
]}

[dev-dependencies]
mockall = "0.9"
