[package]
name = "chip8"
version = "0.1.0"
authors = ["TheBlueFireFox <adrian.hornung@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "chip8_lib"
]

[dependencies]
chip8_lib = { path = "chip8_lib" }
#gui = { path = "gui" }

[profile.release]
panic = 'abort'
